# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Phoenix Inc.
title_separator: "-"
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenido a Ciudad Paragon, la Ciudad de los Héroes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mentalscreen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mentalscreen
locale: "es-ES"

# Theme settings

search: false
search_full_content: false
breadcrumbs: true

author: 
  name: "Julien Turner"
  avatar: "/assets/images/defender.png"
  location: "Rhode Island"

sidebar:
  - title: "CoH homecoming"
    text: "pues un link"

# Build settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-last-modified-at
minimal_mistakes_skin: "air"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include: ["_pages", "_wiki", "_stories"]
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - cheatsheet.md
   - README.md
   - start.bat
   - start_draft.bat

# Jekyll configuration
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  typ: liquid
  path: /tags/

# Plugins configuration
last-modified-at:
    date-format: '%d-%b-%y'

# Collections
collections:
  wiki:
    sort_by: title
  stories:
    sort_by: title

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
  # _stories
  - scope:
      path: "_stories"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      sidebar:
        nav: "stories"
  # _wiki
  - scope: 
      path: "_wiki"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      sidebar:
        nav: "wiki"
  # _posts
  - scope: 
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true